### ISSUE TITLE
Missing 'Cancel' button when user edit their product post.

### ISSUE THREAD

**Issue by TranHuuTam** [fongfan999/foxfizz#7]
![image](https://cloud.githubusercontent.com/assets/22553835/21462472/227e0924-c98f-11e6-8d01-bdb5acac9953.png)

When you edit the 'product write', don't want to save it and quit. It's don't have these function name 'Cancel'.

**Comment by fongfan999** [comment]
Everything is not changed except you click on "Cập nhật", so you can go to Home page, go back or something like this.
