### ISSUE TITLE
Can't Update Information After Using Edit Account

### ISSUE THREAD

**Issue by TranHuuTam** [fongfan999/foxfizz#8]
![image](https://cloud.githubusercontent.com/assets/22553835/21466700/124ca340-ca06-11e6-816d-38c978fd9f0e.png)

I was already edit my Telephone Number, but then when I find the button Update to save my info, these button and function can't help me to do it.
So I feedback to you.

**Comment by fongfan999** [comment]
System is using client side validation, just focus out the input
